### ISSUE TITLE
Installation instructions missed

### ISSUE THREAD

**Issue by angelborroy-ks** [deas/contentreich-eml#5] opened 2016-06-16 14:36 UTC
IMO there is a missing note to installing in 5.0+

`alfresco-global.properties` parameters from [repo module](https://github.com/deas/contentreich-eml/blob/master/contentreich-eml-repo/src/main/resources/alfresco/module/contentreich_email/alfresco-global.properties) must be copied to Alfresco local `/opt/alfresco/tomcat/shared/classes/alfresco-global.properties`

**Comment by deas** [comment] 2016-06-16 14:50
Not sure about it, but are you sure the extension depends on 5.0+?

However, mentioning a supported version surely won't hurt.

Regarding `alfresco-global.properties`: I don't want a requirement to copy anything to `shared/classes/alfresco-global.properties`. I want basic functionality to work out of the box, and the settings from the module should address this. How can I reproduce an issue without copying things around?

**Comment by angelborroy-ks** [comment] 2016-06-16 15:31
I've installed Alfresco 5.0.d by using default Alfresco installer on a Mac OS. Then, I've copied both JARS to alfresco and share `WEB-INF/lib` folders and after re-starting classic no rendered message appears in document detail page:

```
This document can't be previewed.
Click here to download it.
```

However, if I include those lines in my local `alfresco-global.properties` EML is rendered after re-starting. 

I've applied these `alfresco-global.properties` inside Alfresco modules by using AMP packages without problems since some time ago. However, it seems that using JAR package doesn't provide that feature.

**Comment by deas** [comment] 2016-06-17 09:54
Seems I cannot reproduce the issue.

Tried and dropped the jars into a virgin 5.0.d, deployed the share extension module, dropped an rfc822 eml file and went to the details page. PDF preview worked for me.

**Comment by angelborroy-ks** [comment] 2016-06-17 10:04
I'll try again later.

Maybe it's related to OS? A guy from the IRC was complaining also about this problem. He was using Windows 7.

Let me investigate this issue further

**Comment by angelborroy** [comment] 2016-07-01 14:11
Sorry, I can't provide a predictable environment to reproduce that issue.

Maybe we can close this by now. I'll reopen this in the future if needed.

Thanks

**Closed as completed** 2017-08-28 09:45 UTC
